name: Run Tests

on:
  pull_request:
  push:
    branches: [master]
    

jobs:      
  tests:
    name: Run OTP tests
    runs-on: ubuntu-latest
    steps:
      - name: Add custom settings
        run: |
          mkdir -p $GITHUB_WORKSPACE/.m2
          echo """<settings xmlns="http://maven.apache.org/SETTINGS/1.0.0" 
              xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
              xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0
                                http://maven.apache.org/xsd/settings-1.0.0.xsd">
              <mirrors>
                <mirror>
                  <id>onebusaway-releases</id>
                  <mirrorOf>onebusaway-releases</mirrorOf>
                  <url>http://nexus.onebusaway.org/content/repositories/releases/</url>
                  <blocked>false</blocked>
                </mirror>
                <mirror>
                  <id>public.onebusaway.org</id>
                  <mirrorOf>public.onebusaway.org</mirrorOf>
                  <url>http://nexus.onebusaway.org/content/groups/public/</url>
                  <blocked>false</blocked>
                </mirror>
              </mirrors>
            </settings>
          """ > $GITHUB_WORKSPACE/.m2/settings.xml

      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: 8
          settings-path: ${{ github.workspace }}/.m2 # location for the settings.xml file

      - run: mvn --version

      - uses: actions/checkout@v2
        with:
          repository: mbta/opentripplanner
          path: ${{ github.workspace }}/OTP
      
      - uses: actions/checkout@v2
        with:
          repository: mbta/onebusaway-gtfs-modules
          path: ${{ github.workspace }}/onebusaway-gtfs-modules
          fetch-depth: 1

      - run: find .

      - name: Install onebusaway-gtfs-modules
        run: |
          pushd ${{ github.workspace }}/onebusaway-gtfs-modules
          mvn -Dmaven.repo.local="${{ github.workspace }}/.m2" clean install -Dmaven.test.skip=true -Dgpg.skip -Dmaven.javadoc.skip=true -Dlicense.skip=true
          popd
      
      - name: Run OTP tests
        run: |
          mvn -Dmaven.repo.local="${{ github.workspace }}/.m2" clean test -Dgpg.skip -Dmaven.javadoc.skip=true
        working-directory: ${{ github.workspace }}/OTP
